version: '3.8'

services:
  app:
    container_name: server
    image: 'frontend'
    build:
      context: .
    ports:
      - 100:100
  db:
    container_name: mysql
    image: 'mysql:latest'
    environment:
       MYSQL_DATABASE: 'node'
       MYSQL_USER: 'node'
       MYSQL_PASSWORD: 'node'
       MYSQL_ROOT_PASSWORD: 'node'
    ports:
      - 13306:3306
    volumes:
      - testvol:/var/lib/mysql

  mongodb :   
    container_name : mongodb 
    image: 'mongo'
    ports:
      - 27017:27017
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
    #src to dest
      - cubos:/data/db
      - mongodb_config:/data/configdb
volumes:
  testvol :
  cubos : 
  mongodb_config :